# dot/select operator si'
keys('\<C-n>\<C-n>\<C-n>\<C-n>')
keys('w')
keys('changed_word')
keys('\<Esc>')
keys('\<Esc>')
keys('ggA\<Tab>')
keys('text')
keys('\<Esc>')
keys('0j\<C-Down>\<C-Down>')
keys('.')
keys('0dw.~...')
keys('\<Esc>')

keys("6Gf'l")
keys('\<C-n>\<C-n>')
keys("si'")
keys('w')
keys('change')
keys('\<Esc>')
keys('\<Esc>')
